### PR TITLE
Avoid hang after installing VS 2017 (15.3) extension

### LINKED ISSUE #7: AppDomain.Unload hangs after installing VS 2017 extension
After updating Visual Studio 2017, VsixUtil started hanging after (apparently successfully) installing a VS 2017 extension. It's hanging on the `AppDomain.Unload` method.

Here are the active threads after installing a VS 2015 extension (before `AppDomain.Unload` completes sucessfuly):

image

Here are the active threads after installing a VS 2017 extension (before `AppDomain.Unload` is called and hangs):

image

Here are the active threads after it has hung:

image

Can you see any clues there?

I'm most suspicious of the `GC Finalizer Thread`, which remains on `ApplicationInsights.Channel.FlushManager.FlushManager.Flush`. What do you think?

image

### PR DESCRIPTION
**Pull request by jcansdale**
Depends on #6.

`AppDomain.Unload` started hanging after installing VS 15.3.

Since we're using app domains for assembly binding (not to unload assemblies), we don't really need to call `AppDomain.Unload`.

This PR avoids calling `AppDomain.Unload`. It leaves the original code in place so it's obvious it's a workaround.

Fixes #7.

### CODE REVIEW

**Comment by jcansdale** [comment]
It seems extensions only end up getting enabled when `AppDomain.Unload` is called (even if it doesn't complete).

image

So much for my workaround. 😭

**Comment by jcansdale** [comment]
Actually, it looks like extensions only end up enabled when when `AppDomain.Unload` is called on the *Main* thread! 😭 So much for `AppDomain.Unload` on a sacrificial thread. 😉 

Any suggestions @jaredpar? I'm out of ideas.

**Comment by jaredpar** [comment]
I think the disabled flag may be a red herring here. I've seen that a bunch with VsVim. Just seems to happen when you do a lot of extension development.

Have you tried on a clean machine? I'm imagining it will work.

**Comment by jcansdale** [comment]
@jaredpar,

It is very strange, but I've tried it on a clean machine and it seems to behave the same. 😢 

Have you tried using `VsixUtil` on VS 2017 recently? This only seems to be an issue on 15.3 and later.

I've added a `/skip_unload` switch that will simply skip the call to `AppDomain.Unload`. This allows VS 2017 installs to complete, but they end up disable. Without the switch it seems to install correctly, but you have to `Ctrl-C` the process. What a pain.

**Comment by jcansdale** [comment]
@jaredpar, this finally appears to be working.

Extensions can be successfully installed (and enabled!) on VS 2017 if the default app domain is used. This can only be done for a single set of assembly versions, but this doesn't matter because there is only an issue with VS 2017 15.3. 😄 

I've special cased it to not use an app domain when installing for VS 2017, but all other versions and tool actions will continue to create a new app domain.

I've tested installing for multiple versions of VS 2017, and this also seems to work.

**Comment by jaredpar** [comment]
Thanks for doing this work!

**Pull request merged**
